select * from customer limit 2

-- revenue generated by male and female
SELECT gender,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

--which customer used a discount but still spend more than the average
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount)
    FROM customer
);

--top 5  products with the highest average review rating
select item_purchased, ROUND (AVG(review_rating::numeric),2) as "Average Rating" from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5

-- average purchase amount between standard and express
select shipping_type,
ROUND (AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

-- does subscribed customer spend more? compare average spend and total revenue
-- between subscriber and non subscriber
select subscription_status,
count(customer_id) as "total customrers",
round(avg(purchase_amount),2) as "avg_spend",
round(sum(purchase_amount),2) as "total_revenue"
from customer
group by subscription_status
order by total_revenue, avg_spend desc 

-- products have the highest percentage of purchase when the discount is applied
SELECT item_purchased,
ROUND(
    100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
    / COUNT(*),
    2
) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--number of previous purchase and show the count of each segment
with customer_type as(
select customer_id, previous_purchases,
case
when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as customer_segment
from customer
)
select customer_segment, count(*) as "number of customers"
from customer_type
group by customer_segment

-- top 3 most purchaed product within each category
with item_count as(
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count (customer_id) desc)as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_count
where item_rank<=3


---customers who are repeated buyers more than 5 times are also the subscribed customer
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5 
group by subscription_status

-- revenue by age group; 		
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group 
order by total_revenue desc
